<?php

/**
   * Provide a select options component to Webform. The values are
   * populated via a call to _webform_userlist_get_users, which returns
   * an array of users.
 */
function webform_userlist_webform_select_options_info() {
  $items = array();
  if (function_exists('_webform_userlist_get_users')) {
    $items['users'] = array(
      'title' => t('Users'),
      'options callback' => '_webform_userlist_get_users',
    );
  }
  return $items;
}

/**
 * Returns an array of Users.
 *
 * @return array
 */
function _webform_userlist_get_users() {
  $query = db_select('users', 'u')
    ->fields('u', array('name', 'uid'));
  $results = $query->execute();
  // dpq($query); // Display the query.
  // dpr($results); // Display the query result.
  $users = array();
  foreach($results->fetchAll() as $user) {
    if($user->uid > 1) {
      $users[$user->uid] = $user->name;
    }
  }
  return $users;
}
